name: Test mxenv

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Install project
        run: make install

      - name: Run tests
        run: make test
